mahasewa/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import pages.urls as index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('pages.urls', 'pages'), namespace='pages')),
]

pages/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^about/', about, name='about'),
    url(r'^katalog/', katalog, name='katalog'),
    url(r'^apartment/(?P<aptId>[0-9]+)',apartment, name='apartment'),
    url(r'^room/(?P<roomId>[0-9]+)',room, name='room'),
    path('blog/', blog, name='blog'),
    url(r'^blog/(?P<blogId>[0-9]+)', blog_detail, name='blog_detail')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models

# Create your models here.
class Apartment(models.Model):
	name = models.CharField(max_length=20, blank=False)
	address = models.TextField(blank=False)
	descTextbox = models.TextField(blank=False,verbose_name='Description')
	image = models.ImageField(upload_to = "static/images/apartment", default=" " )
	location = models.CharField(max_length=50, blank=False, default="not set")
	def __str__(self):
		return self.name

class Room(models.Model):
	no = models.CharField(max_length=20, blank=False)
	apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
	tower     = models.CharField(max_length=1)
	floor = models.CharField(max_length=20, blank=False)
	descTextbox = models.TextField(blank=False,verbose_name='Description')
	pricePlaceholder = models.CharField(max_length=20, blank=False,verbose_name='Price')

	def __str__(self):
		return self.no

class RoomImage(models.Model):
	room = models.ForeignKey(Room, related_name='images', on_delete=models.CASCADE)
	image = models.ImageField(upload_to = "static/images/room" )

class AptFacility(models.Model):
	apartment = models.ForeignKey(Apartment, related_name='facility', on_delete=models.CASCADE)
	facilityTextbox = models.CharField(max_length=20, blank=False,verbose_name='Facility')
	image = models.ImageField(upload_to = "static/images/facilityLogo", default= "null")

class RoomFacility(models.Model):
	apartment = models.ForeignKey(Room, related_name='facility', on_delete=models.CASCADE)
	facilityTextbox = models.CharField(max_length=20, blank=False,verbose_name='Facility')
	image = models.ImageField(upload_to = "static/images/facilityLogo", default= "null" )
class Contact(models.Model):
	Name = models.CharField(max_length=20, blank=False)
	phoneNum = models.IntegerField()

class Testimonial(models.Model):
	Name = models.CharField(max_length=255, blank=False)
	role = models.CharField(max_length=255, blank=False)
	textBox = models.TextField(blank=False, verbose_name='Description')

	def __str__(self):
		return self.Name

class Blog(models.Model):
	title = models.CharField(max_length=100, blank=False)
	writer = models.CharField(max_length=50, default='Anonymous')
	body = models.TextField()
	thumbnail = models.ImageField(upload_to = "static/images/blog")
	created_at = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.title

pages/views.py
from django.shortcuts import render
from .models import *
from django.core.paginator import Paginator
# Create your views here.
def index(request):
	response = {}
	response['posts'] = Room.objects.all()
	response['apart'] = Apartment.objects.all()
	response['testimonial'] = Testimonial.objects.all()
	return render(request, 'index.html', response)

def about(request):
	response = {}
	return render(request, 'about.html', response)

def katalog(request):
	response = {}
	response['apt'] = Apartment.objects.prefetch_related('room_set')
	return render(request, 'katalog.html', response)

def apartment(request,aptId):
	response= {}
	response['apt'] = Apartment.objects.prefetch_related('room_set').get(id=aptId)
	return render(request, 'apartment.html', response)

def room(request,roomId):
	response= {}
	response['room'] = Room.objects.get(id=roomId)
	response['room_lain'] = Room.objects.all()
	return render(request, 'room.html', response)


def blog(request):
	blog_list = Blog.objects.all()
	paginate = Paginator(blog_list, 5)
	page = request.GET.get('page')
	blogs = paginate.get_page(page)
	return render(request, 'blog.html', {'blogs': blogs})

def blog_detail(request, blogId):
	response = {}
	response['blog'] = Blog.objects.get(id = blogId)
	return render(request, 'blog_detail.html', response)

pages/templates/index.html

{% extends "pages/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
   <section class="hero" id="hero">
       {% include "pages/partials/header.html" %}
       <div class="container">
            <div class="header-table">
                <div class="header-wrapper">
                        <h1 class="header-title" style="margin-bottom:0;"><strong>Cari Kamar di <span class="rotate"> {% for i in apart %} {{i.name}} {% endfor %} </span><strong></h1>
                    <h2 class="whath2">Depok based property and business consultant</h2>
                    <div class="header-subtitle">
                    <a href="{% url 'pages:katalog' %}" class="subtitle-wrapper" style="text-decoration:none; color:black;">
                        <p>Cari Kamar Sekarang    <img class="arrow" src="{% static 'assets/arrow.svg' %}"></p>
                    </a>
                </div> <!-- /.header-wrapper -->
            </div>
        </div> <!-- /.container -->
   </section>
   <section class="about">
    <div class="row">
         <div class="col-sm-3">
            <span class="helper"></span>
    <img class="logo-left" src="{% static 'assets/full_logo.svg' %}">
    </div>
    <div class="col-sm-9">
                    <span class="helper"></span>
        <div class="whatwrapper">
             <h1 class="whath1">What is Mahasewa</h1>
        <p class="whatp">Are asset management and marketing real-time platform that integrated with a smart system technology.</p>
        <div class="readmore">
            <a href="{% url 'pages:about' %}" class="readmore-wrapper" style="color:white; text-decoration:none; margin-left:8%; margin-top:2%;">
                        <p>Baca Selengkapnya</p>
                    </a>
        </div>
        </div>
    </div>
    </div>
   </section>
   <section class="why" id="why">
       <div class="row">
           <div class="col-12" style="padding-top: 2.5%; padding-bottom: 5%;">
               <h1 class="whath1" style="text-align: center;">Why Mahasewa</h1>
           </div>
       </div>
       <div style="padding-left: 5%; padding-right: 5%" class="row">
       <div style="padding-bottom: 5%;" class="col-sm-6" >
        <table class="wrapper">
  <tr>
    <td><img src="{% static 'assets/nyaman.svg' %}" alt="" /></td>
  </tr>
</table>
        <h2 class="hWhy">Nyaman</h2>
        <p class="pWhy">Kenyamanan bagi anda adalah prioritas kami. Kami akan memastikan bahwa pengguna dan pemilik unit mendapatkan kenyamanan yang diinginkan.</p>
           </div>
         <div style="padding-bottom: 5%;" class="col-sm-6">
<table class="wrapper">
  <tr>
    <td><img src="{% static 'assets/terjangkau.svg' %}" alt="" /></td>
  </tr>
</table>                    <h2 class="hWhy">Terjangkau</h2>
        <p class="pWhy">Mahasewa menyediakan harga termurah bagi unit yang disewakan yang disesuaikan dengan kantong mahasiswa</p>
           </div>
         
           </div>
   </section>
{% comment %} services {% endcomment %}
<section class="services" id="services">
    <div class="row">
           <div class="col-12" style="padding-top: 2.5%; padding-bottom: 5%;">
               <h1 class="whath1" style="text-align: center;">Services</h1>
           </div>
       </div>
       <div style="padding-left: 5%; padding-right: 5%" class="row">
       <div style="padding-bottom: 5%;" class="col-sm-3" >
        <table class="wrapper">
  <tr>
    <td><img class="fac-pic" src="{% static 'assets/room_service.jpg' %}" alt="" /></td>
  </tr>
</table>
        <h2 class="hWhy">Room Services</h2>
           </div>
         <div style="padding-bottom: 5%;" class="col-sm-3">
<table class="wrapper">
  <tr>
    <td><img class="fac-pic" src="{% static 'assets/laundry.png' %}" alt="" /></td>
  </tr>
</table>                    
<h2 class="hWhy">Laundry</h2>
           </div>
         <div style="padding-bottom: 5%;" class="col-sm-3">
<table class="wrapper">
  <tr>
    <td><img class="fac-pic" src="{% static 'assets/wifi.jpg' %}" alt="" /></td>
  </tr>
</table>                    
<h2 class="hWhy">Wi-Fi Provider (coming soon)</h2>
           </div>
           <div style="padding-bottom: 5%;" class="col-sm-3" >
        <table class="wrapper">
  <tr>
    <td><img class="fac-pic" src="{% static 'assets/smart.jpg' %}" alt="" /></td>
  </tr>
</table>
        <h2 class="hWhy">Smart System</h2>
           </div>
           </div>
</section>


   <section id="listing" class="listing" style="background-color: #F3F3F3; padding-bottom:.6rem;">
        <div class="row" style="padding-left: 5%;">
           <div class="col-12" style="padding-top: 2.5%; padding-left: 5%;">
               <h1 class="whath1" style="text-align: left;">What We Offer</h1>
           </div>
                  </div>
           {% if posts %}
           <div style="padding-left: 5%; padding-right: 5%; padding-bottom: 1%;" class="slider">
                {% for i in posts %}
  <div class="card">
    <div class="crop">
          <img src="{{i.images.first.image.url}}" style="width:100%">
    </div>
  <div class="container" style="min-height: 32vh;">
    <h4 style="font-size: 4vh; text-align: center;" class="whath1"><b>{{ i.apartment.name }}  {{i.no}}</b></h4>
    <p style="font-size: 2vh;" class="pWhy">{{ i.descTextbox }}</p>
  </div>
  <a href="{% url 'pages:room' i.id %}" class="selengkapnyaWrapper">
          <p class="sButton">Baca Selengkapnya</p>
  </a>
</div>
                {% endfor %}
            </div>
            <div style="margin-left: 7%; margin-top: 1%;" class="readmore">
            <div class="readmore-wrapper" style="margin-left:8.7%;">
                        <a href="/katalog/" style="color:white;"><p style="left :4%;">Lihat semua kamar</p></a>
                    </div>
        </div>
                {% endif %}


   </section>
   <section id="testi" class="testi">
        <div class="row" style="padding-left: 5%;">
           <div class="col-12" style="padding-top: 2.5%; padding-left: 4%; margin-bottom : 5%; ">
               <h1 class="whath1" style="text-align: left;">What They Said</h1>
           </div>
        </div>
           
           {% if testimonial %}
           <div class="row">
              {% for i in testimonial %}
                <div class="col-sm-5 testibox">
                  <p class="nameBox"> {{i.Name}} </p>
                  <p class="roleText"> {{i.role}} </p>
                  <p class="pTesti"> {{i.textBox}} </p>
                </div>
              {% endfor %}
           </div>
           {% endif %}
   </section>
<style type="text/css">
.fac-pic {
  width : 50%;
}
.nameBox {
  color: #121212;
  font-family: Open Sans;
font-style: normal;
font-weight: bold;
line-height: normal;
font-size:3rem;
}
.testibox {
  min-height: 25vh;
  margin-right: 2rem;
  margin-left : 5%;
}
a {
    
    text-decoration:none !important;
}
.whath2 {
    margin-top: 0;
    margin-bottom:2rem;
    font-family: Open Sans;
    font-style : normal;
    font-weight: bold;
    line-weight: normal;
    font-size : 2.5rem;
    color : #FAFAFA;
}
.wrapper {
   height:100%;
   width: 100%;
   margin: 0;
   padding: 0;
   border: 0;
}
.wrapper td {
   vertical-align: middle;
   text-align: center;
}

html,body
{
    overflow-x: hidden;
}

section {
    padding-right: 0;
    margin-right: 0;
    width:100vw;
}

    .hero
{
    background: url('{% static 'assets/hero.png' %}');
    background-repeat: no-repeat;
    background-position: center center;
    background-size: cover;
    -o-background-size: cover;
    -moz-background-size: cover;
    -webkit-background-size: cover;
    background-attachment: fixed;
    -o-background-attachment: fixed;
    -moz-background-attachment: fixed;
    -webkit-background-attachment: fixed;
    height: 100vh;
    color: #FFF;


}
    .about
{
    background-color: #FFF;
    padding-bottom: 5%;

}
    .why
{
    background-color: #F3F3F3;

}
.header-wrapper {
    position: absolute;
left: 5%;
top: 40vh;
margin-right: 5%;
}
.header-title {
font-family: Open Sans;
font-style: normal;
font-weight: 800;
line-height: normal;
font-size: 4.5vw;
color: #FAFAFA;
}
.header-subtitle {
    position: absolute;
width: 257px;
height: 40px;
background: #F1F1F1;
opacity: 0.8;
border-radius: 60px;
}
.subtitle-wrapper {
    display: inline-block;
margin-top: 3%;
margin-left: 5%;
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 20px;
color: #121212;
}
.arrow {
    width: 7%;
}

.logo-left {
    max-width: 100%;
    height: auto;
    padding-left: 15%;
    padding-top: 15%;
    margin: auto;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}

.whath1{
    font-family: Open Sans;
font-style: normal;
font-weight: bold;
line-height: normal;
font-size: 4vw;

color: #121212;
}
.whatp {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: justify;
}
.whatwrapper {
    padding-top: 5%;
    padding-right: 5%;
}
.pWhy {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: center;
color: #121212;
}

.pTesti {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
text-align: justify;
font-size: 12pt;
color: #121212;
}

.sButton {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: center;
font-size: 2vh;
padding: 3% 3% 3% 3%;
color: #999999;
}

.sButton:hover {
    font-family: Roboto;
font-style: bold;
font-weight: bold;
line-height: normal;
font-size: 12pt;
text-align: center;
font-size: 2vh;
padding: 3% 3% 3% 3%;
}

.readmore{
width: 183px;
height: 28px;
background: #000;
border-radius: 60px;
margin-bottom: 5%;
}
.readmore-wrapper {
    display: inline-block;
margin-top: 3%;
margin-left: 10%;
text-align: center;
font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-decoration: none !important;
color: #FFF;
}
.hWhy {
    text-align: center;
    font-family: Open Sans;
    font-style: bold;
    font-weight: bold;
    line-height: normal;
    font-size: 2.7vw;
    color: #121212;
}
.card{
    /* Add shadows to create the "card" effect */
    box-shadow: 0px 2px 12px rgba(0, 0, 0, 0.2);
    transition: 0.3s;
    width: 30vw;
    min-height: 60vh;
    border-radius: 3%;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}
.crop {
    height: 50%;
    overflow: hidden;
}
/* Add some padding inside the card container */
.container {
    padding: 2px 16px;
    width: 100%;
}
.selengkapnyaWrapper {
    border-top: 2px solid #CCCCCC;
}
.selengkapnyaWrapper:hover {
    background: #F3F3F3;
    border-top: 2px solid #F3F3F3;
}
.slick-slide {
    margin-left: 0.5%;
    margin-right: 0.5%;
}
.roleText{
  font-family: Open Sans;
  font-style: normal;
  line-height: normal;
  font-weight: 600;
  font-size: 12pt;
color: #3C7BBE;
}
.footerLinks {
font-family: Roboto;
font-style: normal;
font-weight: 100;
color: #FAFAFA;
}
@media only screen and (max-width: 768px) {
  .namebox {
    font-size : 15pt;
  }
    .header-title {
        font-size: 10vw;
    }
    .whath2 {
        display:none;
    }
.roleText {
  text-align: center;
}
.pTesti {
  text-align: center;
}
.whatwrapper {
    padding-left: 5%;
    padding-right: 5%;
    align-self: center;
}
.whath1{
    font-family: Open Sans;
    text-align: center;
    font-style: normal;
    font-weight: bold;
    line-height: normal;
    font-size: 10vw;

    color: #121212;
}
.logo-left {
    max-width: 100%;
    height: auto;
    margin: auto;
    padding-right: 15%;
}
.hWhy {
  text-align: center;
    font-family: Open Sans;
    font-style: bold;
    font-weight: normal;
    line-height: normal;
    font-size: 8vw;
    color: #121212;
}
.helper {
    display: inline-block;
    height: 100%;
}
#testi {
  height: 100%;
}
</style>
<script>
     $(document).ready(function(){
      $('.slider').slick({
  speed: 300,
  slidesToShow: 3,
  slidesToScroll: 4,
  autoplay: true,
  autoplaySpeed: 3000,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]
      });
    });

    $(".rotate").textrotator({
  animation: "dissolve", // You can pick the way it animates when rotating through words. Options are dissolve (default), fade, flip, flipUp, flipCube, flipCubeUp and spin.
  separator: ",", // If you don't want commas to be the separator, you can define a new separator (|, &, * etc.) by yourself using this field.
  speed:4000 // How many milliseconds until the next word show.
});
</script>
{% endblock %}

pages/templates/pages/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="description" content="Mahasewa">
   <link rel="shortcut icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">
   <meta name="author" content=" ">
   <!-- bootstrap csss -->
   <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
      <link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}"/>
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,300,400,700,600">
 <link href="https://fonts.googleapis.com/css?family=Roboto:Normal,300" rel="stylesheet">
 <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static 'css/style.css' %}">
 <link rel="stylesheet" href="{% static 'css/simpletextrotator.css' %}">
    <!-- Jquery n Bootstrap Script -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <script src="{% static 'js/slick.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/jquery.simple-text-rotator.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>


   <title>
       {% block title %} Mahasewa {% endblock %}
   </title>
</head>
<body>
   <content>
           {% block content %}
               <!-- content goes here -->
           {% endblock %}
   </content>
   <footer>
       <!-- TODO Block Footer dan include footer.html -->
       {% block footer %}
       {% include "pages/partials/footer.html" %}
       {% endblock %}
   </footer>
   {% block javascript %}
   {% endblock %}
<style type="text/css">
a {
  text-decoration: none;
}
a:hover{
    text-decoration: none;
}
</style>
</body>
</html>

pages/templates/pages/partials/footer.html
{% load staticfiles %}
{% load static %}
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<div class="desktop wrap row">
<div class="colWrap col-md-3 col-xs-12">
<img class="logoFoot" src="{% static 'assets/logonav.png' %}">
</div>
<div class="colWrap col-md-3 col-xs-6">
<h2 class="footTitle">Bantuan</h2>
<div class="footerLinks">
<p>Cara Pesan</p>
<p>FAQ</p>
<p>Privasi dan Kebijakan</p>
<p>Syarat dan Ketentuan</p>
</div>
</div>
<div class="colWrap col-md-3 col-xs-6">
<h2 class="footTitle">Media Sosial</h2>
<div style="padding-left:5%;" class="row">
<a href="http://line.me/R/ti/p/@dwu2413c" target="_blank"><img src="{% static 'assets/Line.svg' %}"></a> 
<a href="https://www.instagram.com/mahasewa.id/" target="_blank" > <img src="{% static 'assets/Instagram.svg' %}"></a>
<a href="https://www.facebook.com/mahasewa.id.10" target="_blank"> <img src="{% static 'assets/Facebook.svg' %}"></a>
<a href="https://www.linkedin.com/company/mahasewa-id/about/" target="_blank"> <img src="{% static 'assets/linked_in.svg' %}"></a>
</div>
</div>
<div class="colWrap col-md-3 col-xs-6">
<h2 class="footTitle">Customer Service</h2>
<div class="footerLinks">
<p>Kenzi Anggaraksa</p>
<p>+62 822 9838 9267</p>
<p>mahasewa.id@gmail.com</p>
</div>
</div>
</div>

<!-- mobile layout -->

<div class="mobile wrap row">
<div class="colWrap col-md-12">
<img class="logoFoot" src="{% static 'assets/logonav.png' %}">
</div>
<div class="col-xs-6">
<div class="colWrap">
<h2 class="footTitle">Bantuan</h2>
<div class="footerLinks">
<p>Cara Pesan</p>
<p>FAQ</p>
<p>Privasi dan Kebijakan</p>
<p>Syarat dan Ketentuan</p>
</div>
</div>
<div class="colWrap">
<h2 class="footTitle">Customer Service</h2>
<div class="footerLinks">
<p>Kenzi Anggaraksa</p>
<p>+62 822 9838 9267</p>
<p>mahasewa.id@gmail.com</p>
</div>
</div>
</div>
<div class="col-xs-6">
  <div class="colWrap">
  <h2 class="footTitle">Media Sosial</h2>
  <div style="padding-left:5%;" class="row">
<a href="http://line.me/R/ti/p/@dwu2413c" target="_blank"><img src="{% static 'assets/Line.svg' %}"></a> 
<a href="https://www.instagram.com/mahasewa.id/" target="_blank" > <img src="{% static 'assets/Instagram.svg' %}"></a>
<a href="https://www.facebook.com/mahasewa.id.10" target="_blank"> <img src="{% static 'assets/Facebook.svg' %}"></a>
<a href="https://www.linkedin.com/company/mahasewa-id/about/" target="_blank"> <img src="{% static 'assets/linked_in.svg' %}"></a>
  </div>
  </div>
</div>
</div>

<style type="text/css">
 .wrap {
 	background: #121212;
   padding-bottom: 3rem;
 }
 .colWrap{
 	padding-left: 5%;
 }
 .logoFoot {
 	padding-top: 5%;
 }
 .footTitle {
 	font-family: Roboto;
font-style: normal;
font-weight: bold;
line-height: normal;
font-size: 24px;

color: #FAFAFA;
 }
.mobile {
  display: none;
}
 @media only screen and (max-width: 768px) {
   .desktop {
     display: none;
   }
   .mobile {
     display: block;
     padding: 0% 5% 0% 5%;
   }
 }
</style>

pages/templates/pages/partials/header.html
{% load staticfiles %}
{% load static %}


<!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="{% url 'pages:index' %} " class="navbar-brand">
              <img class="logo" src="{% static 'assets/logonav.png' %}">
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'pages:katalog' %}">Cari Kamar</a></li>
              <li><a href="{% url 'pages:about' %}">About Us</a></li>
              <li><a href="{% url 'pages:blog' %}">Blog</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

<style type="text/css">
  .navbar {
    position: absolute;
    width: 100vw;
  background: none;
  border: none;
  padding: 2.5% 5% 0% 5%;
}
.navbar-default .navbar-collapse, .navbar-default .navbar-form{
  border:none;
}
.navbar-brand {
  display:inline-block;
  float:left;
}

.nav.navbar-nav.navbar-right li a {
    font-family: Open Sans;
font-style: normal;
font-weight: bold;
line-height: normal;
font-size: 20px;

color: #F1F1F1;
}
@media only screen and (max-width: 400px) {
.logo {
  width: 50vw;
  height: auto;
}
}
</style>